services:
  backend:
    build: .
    container_name: task-manager-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:secret@host.docker.internal:5432/taskmanager?schema=public
      JWT_SECRET: your-super-secret-key-change-this